image: gitlab-registry.cern.ch/ci-tools/ci-worker:latex-cc7

compile_CV:

  script:
    - export PATH=/cvmfs/sft.cern.ch/lcg/external/texlive/2016/bin/x86_64-linux:$PATH
    - pdflatex resume.tex
    
  artifacts:
    paths:
      - "*.pdf"

