image: gitlab-registry.cern.ch/ci-tools/ci-worker:latex-cc7

compile_CV:
  before_script:
    - yum install -y texlive ghostscript latexmk libfontenc texlive-collection-latex texlive-*
  script:
    - xelatex -interaction=batchmode resume.tex
  artifacts:
    paths:
      - "*.pdf"
    when: always
  allow_failure: true


